parameters:
- name: agentPool
  type: string
  default: 'MySelfHostedPool'
- name: modelId
  type: string
  default: 'microsoft/phi-2'
- name: llamaCppDir
  type: string
  default: '.\llama.cpp'
- name: buildLlamaCpp
  type: boolean
  default: true
- name: quantizeType
  type: string
  default: 'Q4_K_M'
  values:
  - Q2_K
  - Q3_K_S
  - Q3_K_M
  - Q3_K_L
  - Q4_0
  - Q4_1
  - Q4_K_S
  - Q4_K_M
  - Q5_0
  - Q5_1
  - Q5_K_S
  - Q5_K_M
  - Q6_K
  - Q8_0
  - F16
  - F32

jobs:
- job: ConvertModel
  pool:
    name: ${{ parameters.agentPool }}
  steps:
  - checkout: self
  - script: |
      python --version
      python -m pip install --upgrade pip
      echo "Installing PyTorch (CPU version)..."
      python -m pip install torch --index-url https://download.pytorch.org/whl/cpu
      echo "Installing other dependencies..."
      python -m pip install numpy "transformers>=4.45.1,<5.0.0" "gguf>=0.1.0" "protobuf>=4.21.0,<5.0.0"
      echo "Attempting to install sentencepiece..."
      python -m pip install sentencepiece || echo "SentencePiece installation failed - some models may not convert"
      echo "Verifying installations..."
      python -c "import torch; print('PyTorch version:', torch.__version__)"
      python -c "import transformers; print('Transformers version:', transformers.__version__)"
      python -c "try:^
 import sentencepiece; print('SentencePiece: Available')^
except ImportError:^
 print('SentencePiece: Not available')"
    displayName: 'Install Python Dependencies'
  - ${{ if eq(parameters.buildLlamaCpp, true) }}:
    - script: |
        powershell -File ./build_llama_cpp.ps1 -LlamaCppDir "${{ parameters.llamaCppDir }}"
      displayName: 'Build llama.cpp'
  - script: |
      powershell -File ./convert_model.ps1 -ModelId "${{ parameters.modelId }}" -LlamaCppDir "${{ parameters.llamaCppDir }}" -QuantizeType "${{ parameters.quantizeType }}"
    displayName: 'Convert & Quantize Model'
