parameters:
- name: agentPool
  type: string
  default: 'MySelfHostedPool'
- name: modelId
  type: string
  default: 'microsoft/phi-2'
- name: llamaCppDir
  type: string
  default: '.\llama.cpp'
- name: quantizeType
  type: string
  default: 'Q4_K_M'
  values:
  - Q2_K
  - Q3_K_S
  - Q3_K_M
  - Q3_K_L
  - Q4_0
  - Q4_1
  - Q4_K_S
  - Q4_K_M
  - Q5_0
  - Q5_1
  - Q5_K_S
  - Q5_K_M
  - Q6_K
  - Q8_0
  - F16
  - F32

jobs:
- job: ConvertModel
  pool:
    name: ${{ parameters.agentPool }}
  steps:
  - checkout: self
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true
  - script: |
      powershell -File ./build_llama_cpp.ps1 -LlamaCppDir "${{ parameters.llamaCppDir }}"
    displayName: 'Build llama.cpp'
  - script: |
      powershell -File ./convert_model.ps1 -ModelId "${{ parameters.modelId }}" -LlamaCppDir "${{ parameters.llamaCppDir }}" -QuantizeType "${{ parameters.quantizeType }}"
    displayName: 'Convert & Quantize Model'
